name: pneumonia_diagnostic_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  get: ^4.7.2
  image_picker: ^1.1.2
  pdf: ^3.10.4
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8
  uuid: ^4.3.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: pop
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
